### ISSUE TITLE
[EPIC] ICC rework

### ISSUE THREAD

**Issue by Winfidonarleyan** [WarheadCore/Warhead#9]
# Tasks
1. NPC
- [ ] Add waypoint for `NPC_DEATHBOUND_WARD `
- [ ] Correct npc `nerubar_broodkeeper `

2. GO
- [ ] Correct work start trap for `NPC_DEATHBOUND_WARD `
